services:
  - type: web
    name: kexodrop-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m asyncio run main.py
    envVars:
      - key: BOT_TOKEN
        sync: false  # Set this in the Render dashboard instead of hardcoding here
